#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "thecalculatorspin"
version = "0.1.0"
authors = ["Uffe Hansen <uffe.hansen@gmail.com>"]
description = "HTTP API for the Scientific Calculator WASM component"

[[trigger.http]]
route = "/..."
component = "thecalculatorspin"

[component.thecalculatorspin]
source = "thecalculatorspin-composed.wasm"
allowed_outbound_hosts = []
[component.thecalculatorspin.build]
command = "cargo build --target wasm32-wasip2 --release && wac plug --plug ../the-calculator/the-calculator.wasm target/wasm32-wasip2/release/thecalculatorspin.wasm -o thecalculatorspin-composed.wasm"
watch = ["src/**/*.rs", "Cargo.toml"]
