apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: thecalculaterspin
  namespace: default
spec:
  # IMAGE is substituted by scripts/03-push-and-deploy.sh
  image: "IMAGE_PLACEHOLDER"
  replicas: 1
  executor: containerd-shim-spin
