apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: __APP_NAME__
spec:
  image: "__IMAGE__"
  replicas: 1
  executor: containerd-shim-spin
  imagePullSecrets:
    - name: ghcr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__-proxy
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __APP_NAME__
spec:
  ingressClassName: __INGRESS_CLASS__
  rules:
    - host: __APP_HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: __APP_NAME__-proxy
                port:
                  number: 8080
