additionalArguments:
  - --providers.kubernetesingress.allowExternalNameServices=true
  - --providers.kubernetescrd.allowExternalNameServices=true
  - --ping=true
ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443
service:
  type: ClusterIP
nodeSelector:
  ingress-ready: "true"
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
