package buildbyhansen:the-calculator@0.1.0;

interface calculator {
    calculate: func(expr: string) -> string;
}

world the-calculator {
    import buildbyhansen:arithmetic-calculator/arithmetic@0.1.0;
    import buildbyhansen:trigonometric-calculator/trigonometric@0.1.0;
    import buildbyhansen:moddiv-calculator/moddiv@0.1.0;
    import buildbyhansen:logaritmic-calculator/logaritmic@0.1.0;
    import buildbyhansen:statistics-calculator/statistics@0.1.0;

    export calculator;
}
