package docs:trigonometric-calculator@0.1.0;

interface trigonometric {
    sin: func(degrees: f64) -> f64;
    cos: func(degrees: f64) -> f64;
    tan: func(degrees: f64) -> f64;
    arctan: func(value: f64) -> f64;
}

world trigonometric-calculator {
    export trigonometric;
}
